let BASE_URI;
if (process.env.NODE_ENV === 'production') {
  BASE_URI = "http://192.168.1.4:8090"
} else {
  BASE_URI = "http://localhost:8090"
}
export default {
  URI: {
    PRODUCT: {
      SEARCH_PRODUCT_NAME: `${BASE_URI}/api/mobile-search/search-key-word`,
      SEARCH_PRODUCT_OF_BRANCH: `${BASE_URI}/api/mobile-search/search-product-of-branch`,
    }
  },
  ACTION_TYPE: {
    PRODUCT: {
      SEARCH_PRODUCT_SUCCESS: "PRODUCT_SEARCH_PRODUCT_SUCCESS",
      SEARCH_PRODUCT_FAIL: "PRODUCT_SEARCH_PRODUCT_FAIL",
      SEARCH_PRODUCT_OF_BRANCH_SUCCESS: "SEARCH_PRODUCT_OF_BRANCH_SUCCESS",
      SEARCH_PRODUCT_OF_BRANCH_FAIL: "SEARCH_PRODUCT_OF_BRANCH_FAIL",
      SET_BRANCH: "PRODUCT_SET_BRANCH"
    },
    CURRENT_COORDINATE: {
      SET_CURRENT_COORDINATE: "CURRENT_COORDINATE_SET_CURRENT_COORDINATE"
    }
  }
}